//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawtechPTSystem.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSError", Namespace="http://schemas.datacontract.org/2004/07/SMSServiceAPI")]
    [System.SerializableAttribute()]
    public partial class SMSError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendSMS", ReplyAction="http://tempuri.org/IService1/SendSMSResponse")]
        string SendSMS(string username, string code, System.DateTime now, string supplier, string encodestring, string receivephone, string contentsms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendSMS", ReplyAction="http://tempuri.org/IService1/SendSMSResponse")]
        System.Threading.Tasks.Task<string> SendSMSAsync(string username, string code, System.DateTime now, string supplier, string encodestring, string receivephone, string contentsms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckTransactionNo", ReplyAction="http://tempuri.org/IService1/CheckTransactionNoResponse")]
        string CheckTransactionNo(string username, string code, System.DateTime now, string encodestring, string transactionno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckTransactionNo", ReplyAction="http://tempuri.org/IService1/CheckTransactionNoResponse")]
        System.Threading.Tasks.Task<string> CheckTransactionNoAsync(string username, string code, System.DateTime now, string encodestring, string transactionno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckSMSAmount", ReplyAction="http://tempuri.org/IService1/CheckSMSAmountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LawtechPTSystem.ServiceReference1.SMSError), Action="http://tempuri.org/IService1/CheckSMSAmountSMSErrorFault", Name="SMSError", Namespace="http://schemas.datacontract.org/2004/07/SMSServiceAPI")]
        string CheckSMSAmount(string username, string code, System.DateTime now, string encodestring, string suppliercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckSMSAmount", ReplyAction="http://tempuri.org/IService1/CheckSMSAmountResponse")]
        System.Threading.Tasks.Task<string> CheckSMSAmountAsync(string username, string code, System.DateTime now, string encodestring, string suppliercode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LawtechPTSystem.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LawtechPTSystem.ServiceReference1.IService1>, LawtechPTSystem.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendSMS(string username, string code, System.DateTime now, string supplier, string encodestring, string receivephone, string contentsms) {
            return base.Channel.SendSMS(username, code, now, supplier, encodestring, receivephone, contentsms);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSAsync(string username, string code, System.DateTime now, string supplier, string encodestring, string receivephone, string contentsms) {
            return base.Channel.SendSMSAsync(username, code, now, supplier, encodestring, receivephone, contentsms);
        }
        
        public string CheckTransactionNo(string username, string code, System.DateTime now, string encodestring, string transactionno) {
            return base.Channel.CheckTransactionNo(username, code, now, encodestring, transactionno);
        }
        
        public System.Threading.Tasks.Task<string> CheckTransactionNoAsync(string username, string code, System.DateTime now, string encodestring, string transactionno) {
            return base.Channel.CheckTransactionNoAsync(username, code, now, encodestring, transactionno);
        }
        
        public string CheckSMSAmount(string username, string code, System.DateTime now, string encodestring, string suppliercode) {
            return base.Channel.CheckSMSAmount(username, code, now, encodestring, suppliercode);
        }
        
        public System.Threading.Tasks.Task<string> CheckSMSAmountAsync(string username, string code, System.DateTime now, string encodestring, string suppliercode) {
            return base.Channel.CheckSMSAmountAsync(username, code, now, encodestring, suppliercode);
        }
    }
}
